version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  soap-service:
    build: ./SOAP/language-verifier
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080

  # rest-gateway:
  #   build: ./REST/language-school-rest
  #   ports:
  #     - "8090:8090"
  #   depends_on:
  #     - kafka
  #     - soap-service
  #   environment:
  #     - SERVER_PORT=8090
  #     - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092
  #     - KAFKA_SERVER=kafka:29092
  #     - SOAP_HOST=soap-service
  #   restart: on-failure

  rest-gateway:
    build: ./REST/language-school-gateway
    ports:
      - "8090:8090"
    depends_on:
      - kafka
    environment:
      - SERVER_PORT=8090
      - KAFKA_SERVER=kafka:29092

  rest-worker:
    build: ./REST/language-school-worker
    depends_on:
      - kafka
      - soap-service
    environment:
      - KAFKA_SERVER=kafka:29092
      - SOAP_HOST=soap-service
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092
    restart: on-failure